from app.schemas.community import ReviewKeywordConfigResponse


_KEYWORD_CONFIG_VERSION = "2026-04-29-v1"

_STOP_WORDS = [
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "but",
    "by",
    "for",
    "from",
    "had",
    "has",
    "have",
    "he",
    "her",
    "his",
    "i",
    "if",
    "in",
    "is",
    "it",
    "its",
    "me",
    "my",
    "of",
    "on",
    "or",
    "our",
    "she",
    "so",
    "that",
    "the",
    "their",
    "them",
    "there",
    "they",
    "this",
    "to",
    "was",
    "we",
    "were",
    "with",
    "you",
    "your",
]

_NOISE_WORDS = [
    "accepted",
    "amazing",
    "awesome",
    "channel",
    "content",
    "cool",
    "follow",
    "haha",
    "hello",
    "lol",
    "nice",
    "stats",
    "subscribe",
    "thanks",
    "ucla",
    "video",
    "videos",
    "vlog",
    "vlogs",
    "watching",
    "youtube",
]

_RENTAL_SIGNAL_WORDS = [
    "apartment",
    "apartments",
    "amenities",
    "commute",
    "condo",
    "deposit",
    "garage",
    "hoa",
    "housing",
    "invoice",
    "lease",
    "maintenance",
    "management",
    "mileage",
    "move",
    "moving",
    "neighborhood",
    "noise",
    "parking",
    "pods",
    "price",
    "prices",
    "quote",
    "quoted",
    "rent",
    "rental",
    "safe",
    "safety",
    "storage",
    "traffic",
    "transit",
]

_PHRASES = [
    "camino del sol",
    "extra strength",
    "in unit laundry",
    "long term care",
    "maintenance request",
    "mileage charge",
    "move out",
    "moving quote",
    "parking garage",
    "public transit",
    "rent increase",
    "security deposit",
    "storage container",
]


def get_review_keyword_config() -> ReviewKeywordConfigResponse:
    return ReviewKeywordConfigResponse(
        version=_KEYWORD_CONFIG_VERSION,
        stop_words=_STOP_WORDS,
        noise_words=_NOISE_WORDS,
        rental_signal_words=_RENTAL_SIGNAL_WORDS,
        phrases=_PHRASES,
    )
